#!/bin/sh
PS4='> ${0##*/}[$$]: '
set -e
set -x

mount() { /bin/busybox mount "$@"; }

# emergency trap
trap "exec /bin/sh" EXIT

mount -t proc proc /proc
grep " /dev " /proc/mounts > /dev/null || \
  mount -t devtmpfs devtmpfs /dev
exec < /dev/console > /dev/console 2>&1

eval "$( grep -oE "x6100_multiboot=[^ ]+" /proc/cmdline )"
if [ ! -d "/$x6100_multiboot" ]; then
  x6100_multiboot=Default
fi

mount -o bind "/$x6100_multiboot" /mnt
pivot_root /mnt /mnt/mnt
cd /

mount -t proc proc /proc
umount /mnt/proc
mount -o move /mnt/dev /dev || \
  mount --move /mnt/dev /dev -n

exec /bin/sh -e -c " \
  PS4='> ${0##*/}[\$$]: '; \
  set -x; \
  umount /mnt; \
  exec /sbin/init; \
" # eo /bin/sh
