#!/bin/sh
#
# sshd	Starts sshd.
#

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

umask 077

start() {
	( # fork into subshell to speed up boot

		# Create any missing keys
		/usr/bin/ssh-keygen -A

		printf "Starting sshd: "
		/usr/sbin/sshd
		touch /var/lock/sshd
		echo "OK"

		if [ -d /etc/.git ] && which git > /dev/null; then
			cd /etc
			if git status --short ssh/*key* | grep ^; then
				git add ssh/*key*
				git commit ssh/*key* -m "$0: new ssh host keys"
			fi
		fi
	) &
}
stop() {
	printf "Stopping sshd: "
	killall sshd
	rm -f /var/lock/sshd
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
		start
	;;
  stop)
		stop
	;;
  restart|reload)
		restart
	;;
  *)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
